[component]
structures = [ "content_blocks" ]
label = "Projects"
description = "Projects Section with heading, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Što sve radimo!"
description_html = "Pružamo sveobuhvatna računalna rješenja za različite industrije i potrebe!"
link_url = "/sto-radimo"
show_projects = true